[package]
name = "simpalt"
version = "0.3.7"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", default-features = false, features = [
  "clock",
  "std",
] }
git2 = "0.20.2"

[dev-dependencies]
regex = "1.11.1"
