[package]
name = "simpalt"
version = "0.3.4"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4.31", default-features = false, features = [ "clock", "std" ] }
git2 = "0.18.1"

[dev-dependencies]
regex = "1.10.2"
