[package]
name = "simpalt"
version = "0.2.0"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
chrono = "0.4.23"
git2 = "0.16.1"

[dev-dependencies]
regex = "1.7.0"
