[package]
name = "simpalt"
version = "0.3.1"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4.26", default-features = false, features = [ "clock", "std" ] }
git2 = "0.17.2"

[dev-dependencies]
regex = "1.8.3"
