name: release

on:
  push:
    tags:
      - 'v*'

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare Cargo
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --release --verbose
    - name: Upload asset (UNIX)
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: simpalt-${{ matrix.os }}
        path: ${{ github.workspace }}/target/release/simpalt
    - name: Upload asset (WINDOWS)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: simpalt-${{ matrix.os }}.exe
        path: ${{ github.workspace }}/target/release/simpalt.exe

  release:
    needs: [build]
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Prepare contents
      run: |
        last_tag="$(git describe --tags --abbrev=0 HEAD~1)"
        [ "${last_tag}" ] && last_tag="${last_tag}.."
        echo '**Changes since the last release**' > RELEASE_CHANGES
        git log --format='- %h %s' "${last_tag}${{ github.ref }}" >> RELEASE_CHANGES
        mv simpalt-ubuntu-latest simpalt-ubuntu
        mv simpalt-macOS-latest simpalt-macOS
        mv simpalt-windows-latest.exe simpalt-windows.exe
    - name: Create
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        body_path: ${{ github.workspace }}/RELEASE_CHANGES
        files: |
            ${{ github.workspace }}/simpalt-ubuntu
            ${{ github.workspace }}/simpalt-macOS
            ${{ github.workspace }}/simpalt-windows.exe
